### ISSUE TITLE
Add program in different languages.

### ISSUE THREAD

**Issue by atarax665** [atarax665/VTU-Lab-Programs#5]
This repository is dedicated to help VTU students in learning any language of their choice by solving the programming problems in their academic curriculum. The aim is to make lab programs something more than just bunch of lines being mugged up before practical exams. Contributors are welcomed to code all these familiar lab programs in the language of their choice.

Happy Coding!

**Comment by priyalgupta09** [comment]
can i do this.

**Comment by rishika-singh49** [comment]
I would like to add a program of java 
can i do this ?

**Comment by atarax665** [comment]
> can i do this.

@priyalgupta09 Yes, you can. Choose a language of your choice and get started.

**Comment by atarax665** [comment]
> I would like to add a program of java
> can i do this ?

@rishika-singh49 Yes, you can. Solve the existing problems in Java.

**Comment by LaxmiNyamagoud** [comment]
I would like to add C programs, can you assign this work?

**Comment by VickyGuo0907** [comment]
Hi, I would like to contribute, Solve the problems in Python and Go. Can I do this?
